### PR TITLE
Add text editor

### PR DESCRIPTION
**Pull request by BigBoot**

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
Awesome!

**Comment by TheOfficialFloW** [comment]
Really good implementation. May you also add page skip too?

**Comment by BigBoot** [comment]
Yeah sure, I'd also like to add add/remove lines, but I'm not sure about the controls.
Page skip could be done using the l-/r-trigger, but what should I do about inserting/removing a line?
Do you have a suggestions?

**Comment by TheOfficialFloW** [comment]
I was thinking about either:
* Press RIGHT to insert, LEFT to remove

or:
* Context menu with insert remove options

**Comment by TheOfficialFloW** [comment]
The ime dialog has got ability to use multiline by `SCE_IME_OPTION_MULTILINE`. Using this, we can insert and remove lines.

**Comment by BigBoot** [comment]
Seems like the best solution to me, I'll start working on it.

**Comment by limyz** [comment]
Alternatively do look at PSP Filer's implementation of commands on its text viewer.

up & down: moves the cursor.
* analog up & down: moves the cursor (faster).
* analog left & right: fast scroll left & right (works in FLAT mode).
* LR: (L) loads the previous page (R) loads the next page.
* triangle: change tab stop 4/8 (text is reloaded when in BEND mode).
* square: moves to binary editor.
* circle: toggle FLAT mode / BEND mode.
 * FLAT mode : you can scroll left & right to read text.
 * BEND mode : all text is rearanged to fit the screen size.
 text is reloaded when switching between BEND mode & FLAT mode.
* right: line editor.
   note: edited files will be forced to be shift-jis encoding when it is saved. And, non-shift-jis file and binary file may not be edited & saved correctly.
* start: change encoding
* select: show help
* cross: return to Filer.

**Comment by TheOfficialFloW** [comment]
May you also consider these things that come in my mind?
* Bigger distance between line number and text (same distance as in hex editor maybe)
* Colored line number (adjustable in config of course)
* Tabulator \x09 is not recognized by ime dialog, replace with space?
* Skip utf8 bom
* Correct tabulator in text viewer (the one now does just extend 4 spaces).

**Pull request merged**
