### PR TITLE
Unassisted promotion via ftp custom command PROM <vpkpath>

### PR DESCRIPTION
**Pull request by soywiz**
This PR is related to this issue:
https://github.com/TheOfficialFloW/VitaShell/issues/38

Requires lastest version of libftpvita, that is already merged:
https://github.com/xerpi/libftpvita/pull/16

It is supported in already released VitaOrganizer 0.2:
https://github.com/soywiz/vitaorganizer/
https://github.com/soywiz/vitaorganizer/releases/download/0.2/vitaorganizer-0.2.jar

There is a small minor issue, that after promoting, it doesn't display again the ftp popup.
Tried with this:
```
initMessageDialog(SCE_MSG_DIALOG_BUTTON_TYPE_OK_CANCEL, language_container[FTP_SERVER], vita_ip, vita_port);
dialog_step = DIALOG_STEP_FTP;
```

But was not enough.

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
Where are the files transfered to using your app? Be aware that there's a directory limit on vita fs. It should not reach more than 2 directories, like ux0:ptmp/pkg/: good
ux0:ptmp/pkg/hello: bad

About ftp message bug, did you try closeWaitDialog yet?

**Comment by soywiz** [comment]
What I am doing right now when installing in 1 step:

* Process the VPK, generating a new zip/vpk file with just eboot.bin + sce_sys folder
* I'm uploading that generated smaller file into ux0:/organizer/ID.VPK (didn't wanted to mess with ptmp/pkg directly for now)
* Later I call the `PROM ux0:/organizer/ID.VPK` command (which then starts the whole process of installing, but omits any dialog about being insecure). My APP already checks the eboot.bin to determine wether it has full permissions or limited ones.
* I'm deleting that ID.VPK
* I'm uploading to `ux0:/app/ID/...` the rest of the files

Didn't tried `closeWaitDialog`

**Comment by TheOfficialFloW** [comment]
Ah ok that should work.

**Comment by soywiz** [comment]
Fixed that minor bug related to ftp popup. Tested with VitaOrganizer 0.2 and seems to work fine.

**Comment by TheOfficialFloW** [comment]
Why do you set context mode to opened for ftp message? This is not needed

**Comment by soywiz** [comment]
That was residual code after some tests. I have clean up it already + completion callback stuff.

**Pull request merged**
