### PR TITLE
Feature/bookmarks

### PR DESCRIPTION
**Pull request by abertschi**
My new Vita has arrived so I finally manage to finish this PR.

This implements bookmarks and recent files #436. Three new menu entries are added (screenshot).

Bookmarks of files/folders can be created with New -> New Bookmark

- Within recent files, entries are automatically sorted by date so that the last accessed files appear first.
- L (hold) + square is a shortcut to browse recent files
- R (hold) + square is a shortcut to browse bookmarks
 

VitaShell rocks <3

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
Thanks for your amazing contribution. I've got some small c:hange requests:
- Can you replace the `->` by the real arrow `→`?
- Use a separate context menu called `Bookmarks` or something else which contains the entries `Show Bookmarks` and `Recent files` that is located on top of the context menu (same height as the date).
- Use the left/right buttons on digital pad for shortcuts, since L/R are reserved for page skipping.
Then I'm happy to merge :)

**Comment by abertschi** [comment]
> When in recent files/show bookmarks, pressing O should always return back to normal browser.

Can you elaborate on this? When pressing O, the parent directory is browsed. In case a symlink is resolved, the parent directory is where the symlink was located.

I set the key shortcuts as follows:
- L hold + triangle: recent files
- L hold + square: bookmarks

The file extension is "lnk".

The recent directory is deleted every 14 days.

**Comment by TheOfficialFloW** [comment]
I still think we should not use the L trigger but the left arrow on digital pad for combos, otherwise you cannot return to where you were before.
I mean if you are at `ux0:VitaShell/bookmarks` or `ux0:VitaShell/recent` and press O, you should go back to where you were before. This does not happen when you switch from bookmarks to recent back and forth alot, it is hard to get out and return back to normal browser.

**Comment by abertschi** [comment]
> I still think we should not use the L trigger but the left arrow on digital pad for combos, otherwise you cannot exactly return to where you were before.

You are right. I mistook the keys L and left. The shortcuts are now left + square/triangle.

> I mean if you are at ux0:VitaShell/bookmarks or ux0:VitaShell/recent and press O, you should go back to where you were before. This does not happen when you switch from bookmarks to recent back and forth alot, then it will be hard to get out and return back to normal browser.

ok!

**Pull request merged**
