### PR TITLE
Cosmetic changes to prevent overstretching of overlay menus

### LINKED ISSUE #316: Visual glitch in Electron theme with "Refresh license database"
Since 1.76 and the new top-level context menu item "Refresh license database", the menu background isn't wide enough to contain the text in the Electron theme.
dsc_0606

### PR DESCRIPTION
**Pull request by limyz**
Fixes #316. 
Refer to #314 for initial implementation.

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
What about `Refresh license db` ?

**Comment by limyz** [comment]
The Electron theme doesn't allow strings which are too long to fit in it. Rather than fitting the menus, long strings in the menus will cause it to create a extended transparency.

**Comment by VitaSmith** [comment]
`Refresh database` is way too generic IMO. People already have little clue what `Refresh license database` is about, so if you shorten it to `Refresh database` noone will know this has to do with licenses.

Can you please go with `Refresh license db` as @TheOfficialFloW suggested? The most important word in the feature is "license", not "database".

However, if possible, I'd prefer if themes could be amended to keep the string. This is a user facing menu, and I deliberately went with "database" rather than "db" because we can't assume that VitaShell users will know what "db" stands for... Just hacking around at strings that are too long at random, to remove information that may be vital for the end user doesn't seem like the right way to go IMO...

**Comment by limyz** [comment]
Agreed. The theme have to be amended instead of an one-off solution. In that case, #316 will be left open in the meantime.

**Pull request closed without merging**
