### PR TITLE
Added VitaRW functions for Vitashell

### PR DESCRIPTION
**Pull request by Darkmet98**
Well, I made two modes for vitashell for enabling VitaRW in determinated partitions:
Unsafe Mode (L+R+Square)= Only mount vs0 partition in RW
Brick Mode (L+R+Triangle) = Mount all system partitions in RW.
When, you activated Unsafe or brick mode, you don't need reboot VitaShell, the app mount automaticaly the partitions in RW for edit o delete things.
Thanks to @pedro-javierf and @Raugo for helping me for fix bugs
And very thanks to @tomtomdu80 for make VitaRW

### CODE REVIEW

**Comment by limyz** [comment]
Awesome stuff. This PR will bring it closer to hacker mode in PSPFiler for VitaShell.

**Comment by TheOfficialFloW** [comment]
This feature is too dangerous. If people learn about these combos they will for sure try them, then bricks will happen. Also, what can be modified? Not much I guess

**Comment by limyz** [comment]
@TheOfficialFloW You're right. We probably can leave this feature undocumented, and if enabled, a warning message indicating a high risk of bricking. Again, I leave this to you to simply close this and not merge this PR.

**Comment by TheOfficialFloW** [comment]
I will close the PR with the explaination above. Thanks for the work either way.

**Comment by Darkmet98** [comment]
@TheOfficialFloW  ok no problem, but before put my PR i'm trying to add a mensaje warning in the process but VitaShell crashes and the partitions are dismounted :/
I don't know why the app always crashes.

**Comment by limyz** [comment]
Since you have your fork, you can work on fixing the crash bug. We can always revisit this PR if this feature is required.

**Pull request closed without merging**
