### PR TITLE
Add Support for PlayStation Mobile games in "Refresh Livearea"

### LINKED ISSUE #468: No PSM support in LiveArea refresh
Hello.

Is this possible to add PSM support in the database refreshing?

### PR DESCRIPTION
**Pull request by KuromeSan**
Resolves #468

### CODE REVIEW

**Comment by ricca-meucci** [comment]
#468

**Comment by Rufis01** [comment]
#468

**Comment by TheRadziu** [comment]
#468

**Comment by teakhanirons** [comment]
#468

**Comment by RealYoti** [comment]
@TheOfficialFloW please make a release with this changes (because of auto-update feature that uses your own repo).

**Pull request merged**
