### PR TITLE
Add SFO Reader

### PR DESCRIPTION
**Pull request by theorywrong**
Add an SFO Reader
Maybe add application name next to path (if there is an application)
:+1:

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
Please use the same coding style

**Comment by theorywrong** [comment]
I fixed all the spacing problem caused by gedit, what do you mean with "same coding style" ?

**Comment by TheOfficialFloW** [comment]
Not that it's very important, but for example for all conditions and loops write { on the same line.

for (...) {

Instead of

for (...)
{

Etc.

**Comment by TheOfficialFloW** [comment]
And for pointers write char *p instead of char* p

**Comment by theorywrong** [comment]
It's better like this ?

**Pull request merged**
