### PR TITLE
Add tools context menu (Start button) for future feature

### PR DESCRIPTION
**Pull request by theorywrong**
I added a new context menu when the users use start button, this context menu contains just 'System Information' for now, but can be useful for an future feature

### CODE REVIEW

**Comment by TheOfficialFloW** [comment]
Maybe use a different menu instead? Similar to the dialog, where we have got the menu in the centre

**Comment by theorywrong** [comment]
critical bug in file,i reopen after fix

**Comment by theorywrong** [comment]
why not, a mixture between context menu and dialog box, or other thing ?

**Comment by TheOfficialFloW** [comment]
Be creative. Keep it simple though

**Pull request closed without merging**
