### PR TITLE
Fixed vita toolchain defines, added libpromoter to cmake build

### PR DESCRIPTION
**Pull request by soarqin**
Something in changes:
1. Toolchain defines must be set before 'project' directive to make it working correctly
2. CMAKE_AR/CMAKE_LD and other related variables are set automatically actually, it is only required to set CMAKE_C_COMPILER and CMAKE_CXX_COMPILER. If wanna change these variables, you must set them  in CACHE to override auto-sets
3. Precompiled libpromoter is removed and will be compiled as needed through cmake

### CODE REVIEW

**Comment by BigBoot** [comment]
Regarding 1:
Where did you get that information? 
I can't find anything about it and it breaks the build for me...
The cmake wiki mentions 
> You can also set CMAKE_C_COMPILER_INIT, before any PROJECT() or ENABLE_LANGUAGE() command.

in the description for ```CMAKE_C_COMPILER```, which to me implies, you can only set ```CMAKE_C_COMPILER``` after ```PROJECT()```

**Comment by soarqin** [comment]
@BigBoot I have tested it myself, if set CMAKE_C_COMPILER after PROJECT directive, I will get this error:
```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
System is unknown to cmake, create:
....
```
You can remove the all cmake generated files and run cmake from very beginning to confirm this.
As normal use of toolchain in cmake, it suggests that use -DCMAKE_TOOLCHAIN_FILE=xxxx.cmake, which put the toolchain script content before all scripts in CMakeLists.txt.

**Comment by BigBoot** [comment]
Setting it after project works for me, tried multiple times in completely empty dir..
Anyway I now moved only the cflags down, cause they aren't picked up otherwise.
I also made the compilation of libpromoter not depend on make as the build system.

See 4eb8e67b60c160ba88a7a162da3e4a02e5384e52

**Comment by soarqin** [comment]
@BigBoot if works for you just because you have system GCC in your search path and cmake GCC testing finds your system GCC, try to keep system GCC out of search path and retry, you will find the problem occurs

**Comment by soarqin** [comment]
@BigBoot PROJECT directive with C/CXX as parameter will force a C/CXX compiler check, if you don't set compiler to toolchain before this point, it won't check for compilers set by toolchain setup

**Comment by BigBoot** [comment]
Hmm yeah, I don't feel like uninstalling gcc right now...
But it should work now right?

**Comment by soarqin** [comment]
@BigBoot yeah, if works fine, I have already wrote cmake scripts for other vita projects so I am pretty sure this is the correct way to define toolchain compilers

**Pull request merged**
